### ISSUE TITLE
Export Schema type

### ISSUE THREAD

**Issue by brizer** [jdalrymple/gitbeaker#1218]
**Description**
You should expore type of schema,  so that others  can import. 

**Proposal**
For example,  I have  to  do this:

``` js 
import { GroupSchema } from "@gitbeaker/core/dist/types/services/Groups";
  public async fetchSubGroups(options: Sample): Promise<GroupSchema> {
    const { id } = options;
    const result = await this.core.Groups.all({ id });
    return result;
  }
```

**Comment by jdalrymple** [comment]
Im not sure how to "fix" this. I point to the types [here](https://github.com/jdalrymple/gitbeaker/blob/master/packages/gitbeaker-core/package.json#L43). Any suggestions?

**Comment by brizer** [comment]
Why not refer to `axios· and solve this problem through the adapter？ For example:

``` js
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```

**Comment by jdalrymple** [comment]
haha, is it not exported in that fashion right now?

**Comment by cmckni3** [comment]
Looks like the top level export is missing.

The following do not work:

```
import { RepositoryFileSchema } from '@gitbeaker/core';
```

```
import { RepositoryFileSchema } from '@gitbeaker/node';
```

**Comment by jdalrymple** [comment]
I think i need to add declaration: true!

**Comment by jdalrymple** [comment]
> **Description**
> You should expore type of schema, so that others can import.
> 
> **Proposal**
> For example, I have to do this:
> 
> ```js
> import { GroupSchema } from "@gitbeaker/core/dist/types/services/Groups";
>   public async fetchSubGroups(options: Sample): Promise<GroupSchema> {
>     const { id } = options;
>     const result = await this.core.Groups.all({ id });
>     return result;
>   }
> ```

So I could export the schema but the schema for the response is not that straight forward. It Is a type that is wrapped to account for caramelizing of the response. In the example that you mentioned, you could just use implicit typing:

```ts
public fetchSubGroups({ id }: Sample) {
  return this.core.Groups.all({ id });
}
```

**Comment by jdalrymple** [comment]
Or! you could maybe do something like:

```
public fetchSubGroups({ id }: Sample): ReturnType(this.core.Groups.all) {
  return this.core.Groups.all({ id });
}
```

**Comment by tbarlow12** [comment]
@jdalrymple both implicit typing and importing from a path within `dist/` are anti-patterns

**Comment by zmmille2** [comment]
#1768 Doesn't fix this:

I expect this to work:
`import { EpicSchema } from "@gitbeaker/core";`

But this works instead:
import { EpicSchema } from "@gitbeaker/core/dist/types/services/Epics";

I'm gonna spend a bit in the `tsconfig` and see if I can't fix imports in `core`.

**Comment by jdalrymple** [comment]
> #1768 Doesn't fix this:
> 
> I expect this to work:
> `import { EpicSchema } from "@gitbeaker/core";`
> 
> But this works instead:
> `import { EpicSchema } from "@gitbeaker/core/dist/types/services/Epics";`
> 
> I'm gonna spend a bit in the `tsconfig` and see if I can't fix imports in `core`.

I can go back and change this but explicitly exporting each of these types, but what i mentioned previously still holds. The Schema exports are dynamic depending on the configuration of the service. That's why i mentioned implicit typing or using the ReturnType helper.  

For example:

```typescript
export interface CommitDiscussions<C extends boolean = false> extends ResourceDiscussions<C> {
 ...
  all(
    projectId: string | number,
    commitId: number,
    options?: PaginatedRequestOptions,
  ): Promise<CamelizedRecord<C, DiscussionSchema>[]>;
...
```

The return type is wrapped and altered depending on the configuration, particularly the `camelize` option when you initialize. This value is used to determine the conditional return type and support the correct properties whether camelCase or snake_case

**Comment by zmmille2** [comment]
Just to make sure I understand expectations here, as a consumer of your library, how am I supposed to create epics, projects, etc?

I don't have access to your models. Implicitly using the types doesn't cut it for my use case: I want the type safety of typescript while having a private member variable to store these clients. This will also allow me to mock these services for unit tests.

Right now, this is what my rough understanding is:

```typescript
export class gitLabAgileService extends BaseAgileService {
  private gitLabApi = new Gitlab({/** settings */});

  public constructor(options: AgileProviderOptions, inputService: InputService, logger: Logger) {
    super(options, inputService, logger);
    this.logger = logger;
  }
```

When I highlight over the type of `new Gitlab(...)`, I get the following (do note that I pulled this down to try to muck with it):
```typescript
Mapper<typeof import("/Users/zach/source/personal/gitbeaker/packages/gitbeaker-core/dist/types/services/index"), "Groups" | "GroupAccessRequests" | "GroupBadges" | ... 91 more ... | "Wikis">
```

I'd really like to have a GitLab type in my constructor, so I can register the api with a DI container, but the `Mapper` type is surprising. I don't have access to it through the base import. **Is DI supported?**

Furthermore, when I try to use the `gitLabApi` as follows:
```typescript
  private async createGitLabEpic(groupId: string, backlogItem: BacklogItem): Promise<BacklogItem> {
    const { name, description, children } = backlogItem;

    const epic = await this.gitLabApi.Epics.create(groupId, name, {description, children});
    return this.mapEpicToBacklogItem(epic);
```

The type of `epic` is `Promise<EpicSchema | Camelize<EpicSchema>>`. I have an internal model called `BacklogItem` that's meant to work with a generic backlog item regardless of backing agile service. **How can I write the function I need here?**

```typescript
  private static async mapEpicToBacklogItem(epic: EpicSchema | Camelize<Epicschema>): BacklogItem
```

I'd love to hear more about the ReturnType helper. That surprises me, too: Why not just use the model? Is there some advantage to using the ReturnType helper that is better than just getting access to the models?

Please let me know if I've misunderstood something, and how I need to change how I interact with your library.

**Comment by jdalrymple** [comment]
I hear what you mean. Ill explain a little

**Comment by jdalrymple** [comment]
Give me a little bit and ill address each of your questions :pray:

**Comment by zmmille2** [comment]
Thanks, I am sure maintaining an open source library is a lot of work, I appreciate the responses.

**Comment by jdalrymple** [comment]
Ok, first to explain the types you encountered:

**Mapper**

For bundled imports such as Gitlab, ProjectsBundle, GroupsBundle and UsersBundle, a wrapping function was used to aggregate the settings for each of the services used within them. For example, the UsersBundle includes Users, UserEmails, UserGPGKeys etc services. Instead of having to import each of these and pass them API configuration, the bundle allows you to set the configuration for all of them at once and receive back a object with all these services attached ie:

```typescript
const UserRelatedAPIs = new UsersBundle({config})

const UsersAPI = UserRelatedAPIs.Users
const UserEmailsAPI = UserRelatedAPIs.UserEmails
const UserGPGKeysAPI = UserRelatedAPIs.UserGPGKeys
//... etc
```

Now how does the mapper type come into play? Well to be able to do this wrapping and maintain the typing you would receive at the end of it, there is a type that outlines the relationship between the key and class instance value. It allows for dynamically creating type properties. 

```ts
interface Constructor {
  new (...args: any): any;
}

type Mapper<T extends { [name: string]: Constructor }, P extends keyof T> = {
  [name in P]: InstanceType<T[name]>;
};
```

Which is then used when bundle:

```ts
export interface BundleType<T extends { [name: string]: Constructor }, P extends keyof T> {
  new (options?: any): Mapper<T, P>;
}

export function bundler<T extends { [name: string]: Constructor }, P extends keyof T>(
  services: T,
): BundleType<T, P> {
  return function Bundle(options?: any) {
    Object.entries(services).forEach(([name, Ser]) => {
      /* eslint @typescript-eslint/ban-ts-comment: 0 */
      // @ts-ignore
      this[name] = new Ser(options);
    });
  } as any as BundleType<T, P>;
}
```

There is most likely a better way of doing this, but it was such a pain to get it to work initially, I try to avoid tinkering with it haha. 

>UPDATE: As i was testing this for the explainer above, i did find an issue with the bundling typing so it looks like i will have to take another look. It looks like the conditional typing that is applied to single api exports is missing from these bundles 😢


**DI Support**

Im not sure i completely understand this question. Could you perhaps include an example of how such a situation would look like? Doesnt have to be with this library, just a pseudo example for the idea.

**The epic example**

This is where i noticed the problem i mentioned above. The type you should see after applying configuration would be either: Promise<EpicSchema> OR Promise<Camelize<EpicSchema>> but not the combined or. You can see this if you import the Epic API directly instead of using the Bundled Gitlab Import. This is a bug that needs to be fixed.

**General Schema Exports**

I realize having the explicit exported schemas would be lovely, and it is a very doable task. I will have to think about the best way to go about it though, whether i should move them out of their current files into one large Schema file, or have a folder for this or something. Simply 'exporting * ' from what is there right now wont work i don't think because i them [import *](https://github.com/jdalrymple/gitbeaker/blob/e83969a0de2591d89c39540f5ef5eff85e30b158/packages/gitbeaker-core/src/index.ts#L2), which now would include interfaces (i think, i need to test this theory) breaking calls like [here](https://github.com/jdalrymple/gitbeaker/blob/e83969a0de2591d89c39540f5ef5eff85e30b158/packages/gitbeaker-core/src/index.ts#L105)

**Comment by zmmille2** [comment]
I'm taking a crack at this. I'll poke when I've got a PR up.

**Comment by dcharbonnier** [comment]
Quite complicated to work with this lib for now 

```
type PromiseType<T extends Promise<any>> = T extends Promise<infer U> ? U : never;
type Gitlab = InstanceType<typeof Gitlab>
type ProjectSchema = PromiseType<ReturnType<Gitlab["Projects"]["create"]>>
type GroupSchema = PromiseType<ReturnType<Gitlab["Groups"]["create"]>>
```

**Comment by jdalrymple** [comment]
Ouffff, hopefully have something for you guys soon!

> Quite complicated to work with this lib for now
> 
> ```
> type PromiseType<T extends Promise<any>> = T extends Promise<infer U> ? U : never;
> type Gitlab = InstanceType<typeof Gitlab>
> type ProjectSchema = PromiseType<ReturnType<Gitlab["Projects"]["create"]>>
> type GroupSchema = PromiseType<ReturnType<Gitlab["Groups"]["create"]>>
> ```
> 
> Also the returned types for Groups.all for example is something or a camelized something, why ? as a result the properties of the schema are unknown
