### ISSUE TITLE
Is there a way to set proxy settings ?

### ISSUE THREAD

**Issue by ardole** [jdalrymple/gitbeaker#2014]
Hi !

Trying to use gitbeaker behind a corporate proxy, is it possible ?

### Steps to reproduce

- Behind a corporate proxy
- Any request to Gitlab 
```
const api = new Gitlab({
    host: 'https://gitlab.com',
    token: 'my-token',
});
let projects = await api.Groups.projects("anyid", {maxPages: 2, perPage: 40 });
```

### Actual behavior

As no proxy has been defined...

```
RequestError: getaddrinfo ENOTFOUND gitlab.com
```

Thanks

**Comment by jdalrymple** [comment]
Hmm this is a good question, ill follow up when i have time to tinker

**Comment by jdalrymple** [comment]
It looks like this could be possible in the future, though would require some tweaks. Since we mainly use Got, here is an [example](https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying) of how they extended the basic got request to support proxies. Similar modifications could be made to either a custom requester, or natively in this library

**Comment by TBG-FR** [comment]
I think that feature would be great. I started used your lib because manually creating all request to fit Gitlab API was not really convenient, but now I'm blocked by the corporate proxy...

I'll see if I manage to tweak the code and create a PR !
