### ISSUE TITLE
@gitbeaker/node latest version has got pinned which has a security vulnerability

### ISSUE THREAD

**Issue by alfaproject** [jdalrymple/gitbeaker#2551]
**Description**

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Got allows a redirect to a UNIX socket                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ got                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=11.8.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @gitbeaker/node                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @gitbeaker/node > got                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1075647                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Possible solutions**

Unpin `got` or increment its version number.

...but ideally you would allow to use any fetch-like implementation since you only use basic HTTP requests, can let your clients give an implementation to do a request.

**Comment by jdalrymple** [comment]
The game plan is to remove the reliance on got/ky entirely and use fetch. It was pinned at the time since i couldnt switch this library fully to esm and the new got versions support esm only. Additionally, fetch in node wasnt fully supported yet. Its on the todo list haha. I've leave this here so i dont forget though! 

Technically you can use any fetch implementation through using the @gitbeaker/core and @gitbeaker/requester-utils, however the docs on the manner is lacking. Is youre really keen, see how the @gitbeaker/node is written, its basically a got wrapper and could easily be converted.

**Comment by alfaproject** [comment]
That's fair and I understand that but you can just unpin to `~11.8.5` or `^11.8.5`. The ESM version of `got` is a major version update because they follow semver. And then, later on, when you are ready to switch to another library you can just remove it, ofc

It's the same thing with `node-fetch` if you used it, the latest major version is also ESM but the previous v2 still receives security updates (;
