### ISSUE TITLE
Delete merged branches support ?

### ISSUE THREAD

**Issue by Antoine-Sevec** [jdalrymple/gitbeaker#2992]
Hello, 

First of all thank you for the project it's great ;)

Voila I would have liked to support the method to delete merged branches
https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/branches.md#delete-merged-branches

And I don't think I can do it with gitbreaker unless I'm wrong?

Thanks for your help

**Comment by jdalrymple** [comment]
Hey!! The current version does not support this functionality since it was unfortunately build for an older version of the API, however the latest version that's currently being tested does. You can see the progress on this updated support in #2258. Its a huge MR since the API changed substantially in the last couple years, but the function is called "removedMerged" in the Branches resource. I'm pushing to have a rc version release in a few weeks if all the testing goes well. I update it on the regular so you can see the progress :crossed_fingers:
