### ISSUE TITLE
Implement old Users.search

### ISSUE THREAD

**Issue by ArnaudTA** [jdalrymple/gitbeaker#3315]
**Description**
Support for `Users.search` in @gitbeaker/rest package

Since I moved from @gitbeaker/node `Users.search` is not supported anymore, the `Search('users')` function is not sufficient in my case cause i need more informations from users.

**Proposal**
Re-implement functionality as it was in @gitbeaker/node

I think I don't understand very well your lib to do MR but I'll try.

Thanks in advance !

**Checklist**
- [x] I have checked that this is not a duplicate issue.
- [x] I have read the documentation.

**Comment by jdalrymple** [comment]
Its currently suppored. When calling the all method, just add a search option:

```
await UsersAPI.all({ search: 'John })
```
The update was made to match the way the [docs](https://docs.gitlab.com/ee/api/users.html#for-non-administrator-users) described it to reduce confusion:

>You can also use ?search= to search for users by name, username, or public email. For example, /users?search=John. When you search for a:
- Public email, you must use the full email address to get an exact match. A search might return a partial match. For example, if you search for the email on@example.com, the search can return both on@example.com and jon@example.com.
- Name or username, you do not have to get an exact match because this is a fuzzy search.


It does seem to be missing from the types though, so i will fix that!

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`39.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.2.0) :rocket:
