### ISSUE TITLE
Services to get api parameters

### ISSUE THREAD

**Issue by Demonium** [jdalrymple/gitbeaker#840]
**Description**
Regarding the topic below https://forum.gitlab.com/t/api-data-model-definition/2469
Should be great if we can have a service or additionnal information to get the API model definition to create custom call
Instead of looking the documentation
**Proposal**
adding a service that give up all parameters for each API service

**Comment by jdalrymple** [comment]
Can you give me an example? I do currently export a JSON representation of the API, but it obviously doesn't cover all the things available since the options parameters dont explicitly list every option available

**Comment by Demonium** [comment]
Sure, for example I want to use the project API to create a new one I have to have a look to this page
https://docs.gitlab.com/ee/api/projects.html#create-project and implement in my code every parameters.
Should be better if I can have something like 

`const gitlab = new Gitlab.Gitlab({
    host: 'http://mygitlab',
    token: 'mytoken'
});
var projectParameters = gitlab.Projects.getParameters();
`
in projectParameters I retrieve all the parameters define in the documentation.

but I could also use the same method for others sub class of Gitlab

Does it enought for example ?

**Comment by jdalrymple** [comment]
Hmm, only a small subset parameters are explicitly mentioned in the code, so I'm not sure just how helpful that would be for you. 

Additionally, If youre just looking for the information, this is where typescript can be extremely useful since this library is typed and thus can reveal to you those parameters when youre writing that code.

If youre looking to use the parameters somehow dynamically, like in your example, use projectParameters for something, there IS an export from the core library that does include this [information](https://github.com/jdalrymple/gitbeaker/blob/master/packages/gitbeaker-cli/src/index.ts#L9), *BUT* It isn't an official export and can possibly change in the future.

**Comment by Demonium** [comment]
is it a good start I will ask on gitlab if they will plan to provide something more useful for that kind of request.
I'm not an expert but I found REST API less interesting than OData that can provide this kind of information...
Thanks for your help :)
