### ISSUE TITLE
How do I initialise the client correctly?

### ISSUE THREAD

**Issue by rpuls** [jdalrymple/gitbeaker#872]
Hi, sorry for raising an issue I know this is not an actual issue with the module, but maybe the documentation could be extended a little.

I'm trying to use the basic example, but I'm getting 404
```
rejected promise not handled within 1 second: HTTPError: Response code 404 (Not Found)
extensionHostProcess.js:957
stack trace: HTTPError: Response code 404 (Not Found)
```

I believe it is because I am providing an invalid host url. In the documentation you are only showing:  
```
const api = new Gitlab({
  host: 'http://example.com', // where do I get this actual url ???
  token: 'personaltoken',
});
```
I have tried: `https://gitlab.com/api/v4` and `https://gitlab.com/api/v4/` (also v3) and I am not getting any helpful errors just 404.

I can't find the information about the actual gitlab url that I should be providing. I have also been closely searching: https://docs.gitlab.com/ee/api/api_resources.html#standalone-resources for such a url but can't find it anywhere.

I know that ideally this information should be provided by gitlab but would it be possible for you to add to the readme how to obtain this url?
Would be highly appreciated!

Thanks

**Comment by jdalrymple** [comment]
Hey!

In the [getting started](https://github.com/jdalrymple/gitbeaker#getting-started) section, it outlines the different configuration parameters you can pass to the classes as well as their defaults. If youre trying to access gitlab.com, then you **DO NOT** need to put anything for the host, since the default will be used *https://www.gitlab.com*. This is also true for the version, which defaults to 4.
